"""Initial migration

Revision ID: 0fb15f6631e8
Revises: 9f4d4811e46d
Create Date: 2025-02-16 08:47:31.131558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0fb15f6631e8'
down_revision: Union[str, None] = '9f4d4811e46d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wallet_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('book_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bvn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nin', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('locked_funds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
