"""your_message

Revision ID: 163409b8b211
Revises: a9cea43efd74
Create Date: 2025-02-18 10:27:08.059999

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '163409b8b211'
down_revision: Union[str, None] = 'a9cea43efd74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('transaction_limit_per_transaction', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('transaction_limit_per_day', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'transaction_limit_per_day')
    op.drop_column('users', 'transaction_limit_per_transaction')
    # ### end Alembic commands ###
