"""new column

Revision ID: 4e06450b0576
Revises: 6c907ad9f4af
Create Date: 2025-02-25 11:52:06.532906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e06450b0576'
down_revision: Union[str, None] = '6c907ad9f4af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('narration', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfers', 'narration')
    # ### end Alembic commands ###
