"""Another column

Revision ID: 5295d7663844
Revises: 0b33849cbc59
Create Date: 2025-02-13 16:15:59.838970

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5295d7663844'
down_revision: Union[str, None] = '0b33849cbc59'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('level_1', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level_1')
    # ### end Alembic commands ###
