"""migrate

Revision ID: 62deb15a850e
Revises: f89ddf99febc
Create Date: 2025-02-19 10:40:29.335644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '62deb15a850e'
down_revision: Union[str, None] = 'f89ddf99febc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('date', sa.DateTime(), nullable=True))
    op.drop_column('transfers', 'timestamp')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('transfers', 'date')
    # ### end Alembic commands ###
