"""your message

Revision ID: 924ba24ec5c2
Revises: 2b71dd65f433
Create Date: 2025-02-17 16:06:59.090222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '924ba24ec5c2'
down_revision: Union[str, None] = '2b71dd65f433'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('locked_funds_user_id_fkey', 'locked_funds', type_='foreignkey')
    op.drop_table('users')
    op.drop_table('locked_funds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locked_funds',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('release_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='locked_funds_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='locked_funds_pkey')
    )
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wallet_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('book_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bvn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nin', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('transaction_pin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
