"""your_message

Revision ID: a9cea43efd74
Revises: 347f3fe892fc
Create Date: 2025-02-17 16:37:52.396679

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9cea43efd74'
down_revision: Union[str, None] = '347f3fe892fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('locked_funds', 'id2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('locked_funds', sa.Column('id2', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
