"""migrate

Revision ID: b0fe6a3ec164
Revises: 63d98f8a6cb1
Create Date: 2025-02-19 10:43:06.849316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b0fe6a3ec164'
down_revision: Union[str, None] = '63d98f8a6cb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('date_sent', sa.DateTime(), nullable=True))
    op.drop_column('transfers', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('transfers', 'date_sent')
    # ### end Alembic commands ###
