"""Sync with current database

Revision ID: e97f15811643
Revises: d360bac96668
Create Date: 2025-02-17 15:47:25.160183

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e97f15811643'
down_revision: Union[str, None] = 'd360bac96668'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('account_number', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('password', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_admin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('wallet_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('book_balance', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('bvn', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('nin', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('level_1', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level_2', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('level_3', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('locked_funds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('transaction_pin', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    # ### end Alembic commands ###
