"""migrate

Revision ID: f89ddf99febc
Revises: 91de7fb72c4e
Create Date: 2025-02-19 10:03:15.085305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f89ddf99febc'
down_revision: Union[str, None] = '91de7fb72c4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transfers', sa.Column('transaction_type', sa.String(), nullable=False))
    op.add_column('transfers', sa.Column('transaction_ref', sa.String(), nullable=False))
    op.add_column('transfers', sa.Column('session_id', sa.String(), nullable=False))
    op.add_column('transfers', sa.Column('status', sa.String(), nullable=False))
    op.alter_column('transfers', 'sender_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('transfers', 'receiver_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transfers', 'receiver_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('transfers', 'sender_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('transfers', 'status')
    op.drop_column('transfers', 'session_id')
    op.drop_column('transfers', 'transaction_ref')
    op.drop_column('transfers', 'transaction_type')
    # ### end Alembic commands ###
